# Generated by Django 4.0.4 on 2022-04-22 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='dueTime',
            new_name='prazo',
        ),
    ]
